oss-compass/compass-projects-information

collections/big-data.yml

Add project collection of big data:
- https://github.com/apache/spark
- https://github.com/apache/flink

feat(collection): add collection of big data

---

collections/graph-databases.yml

Add project collection of graph database:
- https://github.com/dgraph-io/dgraph

feat(collection): add collection of graph database

---

collections/message-queue.yml

Add project collection of message queue:
- https://github.com/apache/pulsar
- https://github.com/apache/rocketmq
- https://github.com/apache/inlong

feat(collection): add collection of message queue

---

collections/static-site-generator.yml

Add project collection of static site generator:
- https://github.com/jekyll/jekyll
- https://github.com/gohugoio/hugo
- https://github.com/11ty/eleventy
- https://github.com/vuejs/vuepress
- https://github.com/hexojs/hexo
- https://github.com/getpelican/pelican
- https://github.com/metalsmith/metalsmith
- https://github.com/facebook/Docusaurus
- https://github.com/slatedocs/slate
- https://github.com/gridsome/gridsome
- https://github.com/middleman/middleman
- https://github.com/react-static/react-static
- https://github.com/docsifyjs/docsify
- https://github.com/mkdocs/mkdocs
- https://github.com/sintaxi/harp
- https://github.com/netlify/netlify-cms
- https://github.com/jaspervdj/hakyll
- https://github.com/umijs/umi
- https://github.com/abelljs/abell
- …

feat(collection): add collection of static site generator

---

collections/api-gateway.yml

remove duplicate item in api-gateway collection

---

collections/package-management-tools.yml
collections/terminal.yml

Signed-off-by: neil <msg@nancode.cn>

fix: wrong collection item

---

collections/chrome-extension-development.yml
collections/compression-and-decompression.yml
collections/computational-fluid-dynamics.yml
collections/crawler.yml
collections/discord-bot.yml
collections/domain-specific-language.yml
collections/emacs.yml
collections/emoji.yml
collections/fake-data-generator.yml
collections/fonts.yml
collections/game-emulator.yml
collections/icon-library.yml
collections/illustration.yml
collections/motion-graphics.yml
collections/note-application.yml
collections/obs-studio.yml
collections/quantitative-trading.yml
collections/socket-server.yml
collections/vlc-player.yml
collections/wms.yml

Updated the following collections:
- chrome extension development
- compression and decompression
- computational fluid dynamics
- crawler
- discord bot
- domain specific language
- emacs
- emoji
- fake data generator
- fonts
- game emulator
- icon library
- illustration
- motion graphics
- note application
- obs studio
- quantitative trading
- socket server
- vlc player
- wms

Collections update 0328-2

---

single-repositories/github/markoJS/marko.yml

Reverts oss-compass/compass-projects-information#371

Revert "Updated single-repositories/github/markoJS/marko.yml"

---

collections.yml

below classification files already added
BIOS.yml # BIOS
other-firmware.yml # 其他固件

Update collections.yml with adding firmware  category

---

collections.yml

remove   
- 3d-modeling-and-rendering # 3D 建模和渲染软件 will add to multimedia class
added  
- circuit-breaker # 断路器
- raspberry-pi # 树莓派

Update collections.yml of teir 1 class - hardware

---

collections.yml

Remove “merging technologie 新兴技术”, 
ChatGPT will be moved to AI class.
Adding “cutting edge technologies 前沿技术” 
Tier 2 yml files areready.

Update collections.yml of cutting edge technologies

---

collections.yml
collections/blockchain.yml
collections/serverless.yml

更新Serverless框架为Serverless无服务器，由开发框架大类迁移到服务器应用大类

更新Serverless框架为Serverless无服务器、新增区块链yml文件

---

collections/browser-devtools.yml

从已有的 chrome-devtools.yml Chrome 开发者工具 合并过来

新增浏览器开发者工具yml文件

---

collections/cloud-computing.yml

云计算分类关系为
- ident: virtualization-and-cloud-computing
name: Virtualization and Cloud Computing
name_cn: 虚拟化和云计算
items:
- cloud-computing # 云计算

新增云计算yml文件

---

collections/Metaverse-web3.yml
collections/animation-library.yml
collections/css-framework.yml
collections/ui-library.yml

更新UI库、元宇宙和Web3、动画库、CSS框架yml文件

---

collections.yml

Add three tier 2 classes into  “frontend”
they are both in “frontend” and “web-application-development”  classes.

Add three tier 2 classes into  “frontend”

---

collections.yml

Add tier 1 class -  artificial intellignece 
- mlops # 自动化机器学习，原有2级分类
- deep-learning-framework # 深度学习框架，原有2级分类
- nlp # 自然语言处理，原有2级分类
- computer-vision-face-recognition # 计算机视觉和人脸识别，新增2级分类
- aigc # AI内容生成，包括ChatGPT系列，新增2级分类

Update collections.yml，add tier 1 class AI

---

collections.yml

name_cn: 区块链技术和应用 
with Three tier 2 classes :
- blockchain # 区块链技术
- digital-currency # 数字货币
- nft # NFT非同质化通证

Update collections.yml， add tier 1 class - Blockchain 

---

collections/chart-component.yml

新增图表组件yml文件 

---

collections/workflow.yml

从：
- ident: others
name: Others
name_cn: 其他
items:
- workflow-scheduler # 工作流调度器
合并至：
items:
- workflow # 工作流

新增工作流yml文件

---

collections.yml
collections/android-development-framework.yml
collections/ios-framework.yml

In this PR, a new tier 1 class "handset and mobile application development" was added for mobile apps.
Also, "Android developmemt framework" and "iOS framework" has been changed on their description. because more than framework components were included in yaml files.

Updated collections.yaml, added tier 1 class -- handset and mobile application development

---

collections/common-toolkit.yml

新增常用工具包yml文件 

---

collections/microservice.yml

新增微服务yml文件

---

collections/reporting-tool.yml

新增报表工具yml文件 

---

collections/payment-SDK.yml

新增支付开发包yml文件

---

collections/logging-toolkit.yml

新增日志工具包yml文件

---

collections/regulation-engine.yml

新增规则引擎yml文件 

---

collections/ authority-management.yml

该分类所属一级分类：
ident: development-toolkit

新增权限管理yml文件

---

collections/markdown-toolkit.yml

该分类所属一级分类：
ident: development-toolkit

新增Markdown工具包yml文件

---

collections.yml
collections/one-click-installation-kit.yml

Added tier 1 class “server applications” in collections.yml, 
updated tier 2 class "one click installation kit"  
see detail in commits of related files.

Added tier 1 class “server applications” in collections.yml, updated tier 2 class "one click installation kit" 

---

collections/program-and-script-language.yml

该分类所属一级分类：
ident: development-toolkit

新增编程语言和脚本语言yml文件

---

collections.yml

DevOps class was expanded to a larger view, include more related tools, such as network management tools, system management tools, system monitoring tools, Devops tools. 
for better reflect this change,  the class name "DevOps" was changed to "DevOps and network management and maintaining"

Update collections.yml, new tier 2 classes were added.

---

collections/workflow-engine-and-tools.yml

该分类所属一级分类：
ident: development-toolkit

新增流程引擎及工具yml文件

---

collections/network-service.yml
collections/network-tool.yml

该分类所属一级分类：
ident:development-toolkit
name:开发工具包
name_cn:程序开发工具

新增网络服务和网络工具

---

collections/voice-processing.yml

该分类所属一级分类：
ident:development-toolkit
name:开发工具包
name_cn:程序开发工具

新增语音处理yml文件

---

communities/ao-space.yml
communities/ash.yml
communities/bboss.yml

Related issues: 
https://github.com/oss-compass/compass-projects-information/issues/413
https://github.com/oss-compass/compass-web/issues/218

feat: communities yml file add fields

---

communities/ao-space.yml
communities/ash.yml
communities/bboss.yml

Reverts oss-compass/compass-projects-information#684

Revert "feat: communities yml file add fields"

---

collections.yml

Upgrade existing "search engine" to tier 1 class
adding "code-search" and "full-text-search-engine" into this class

Upgrade existing "search engine" to tier 1 class,  add two other tier 2 class into it.

---

collections/bbs-forum-and-qa-website.yml

该分类所属一级分类：
ident: website-system
name: Website System
name_cn: WEB网站系统

新增BBS论坛及问答网站

---

collections/school-teaching-management.yml

该分类所属一级分类：
ident: website-system
name: Website System
name_cn: WEB网站系统

新增学校管理及教学管理

---

collections/network-and-border-security-products.yml

该分类所属一级分类：
ident: information-security
name: Information Security
name_cn: 信息安全软件

新增网络与边界安全产品

---

collections/customer-relationship-management-CRM.yml

该分类所属一级分类
ident: general-management-software
name: General Management Software
name_cn: 通用管理软件
在原有 crm.yml 文件基础上进行新增

新增客户关系管理（CRM）

---

collections/audio-processing.yml
collections/image-processing.yml

该分类所属一级分类
ident: multi-media-software
name: Multi Media Software
name_cn: 多媒体软件

更新图像处理库，新增音频处理

---

collections/container-registry.yml
collections/video-processing.yml

该分类所属一级分类
ident: multi-media-software
name: Multi Media Software
name_cn: 多媒体软件
视频处理吸收 video-editor.yml，vlc-player.yml

新增视频处理，更新容器镜像注册表失效项目

---

collections/data-mining-and-analysis.yml
collections/dedicated-security-products.yml

数据挖掘对应一级分类
专用安全产品对应一级分类
- ident: information-security
name: Information Security
name_cn: 信息安全软件

新增数据挖掘或分析与专用安全产品

---

collections.yml
collections/cloud-native-storage.yml

Update collections.yml
1. Rename "cloud-native" to "virtualization-and-cloud-computing","云原生、云计算和虚拟化"，to include wider meanings.
2. move "remote-procedure-call # 远程过程调用（RPC）" to "web-application-development" category.
collections/cloud-native-storage.yml
delete  "https://github.com/heketi/heketi” because of its offcial announcement that it is not maintained anymore.

Update collections.yml and collections/cloud-native-storage.yml 

---

collections/vim-derived-editors.yml
collections/word-processing-software.yml
collections/wysiwyg-editor.yml

字处理软件对应一级分类
- ident: office-software
name: Office Software
name_cn: 办公软件

新增字处理软件、更新Vim 衍生编辑器和即见即所得编辑器

---

communities/kurator.yml

Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>

add kurator community repo info

---

communities/kuasar.yml

Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>

add kuasar community repo info

---

collections/3d-printer.yml
collections/printing-and-publishing-software.yml

印刷出版软件属于
- ident: word-language-processing
name: Word and Language Processing
name_cn: 文字语言处理
3D打印属于
- ident: hardware
name: Hardware
name_cn: 硬件

新增印刷出版软件和更新3D打印

---

communities/xline.yml

Add xline community repo info

---

collections/mail-client.yml
collections/mail-server.yml

后续考虑将这两个分类归类到以下一级分类中：
- ident: network-communication-software
name: Network Communication Software
name_cn: 网络通信软件

更新邮件客户端和邮件服务器

---

collections.yml

Below 10 Lv.2 categories were added   
- basic-security-products # 基础类安全产品 - network-and-border-security-products # 网络与边界安全产品 - dedicated-security-products # 专用安全产品 - security-evaluation-and-service-products # 安全测试评估与服务类产品 - security-management-product # 安全管理产品 - privacy-computing # 隐私计算 - cryptography # 密码学 - security-audit # 安全审计 - steganography # 隐写术 - software-composition-analysis # 软件成分分析（SCA）

Update collections.yml adding 10 Lv.2 categories in Security class

---

collections/software-downloading.yml

- ident: network-communication-software
name: Network Communication Software
name_cn: 网络通信软件

新增软件下载辅助工具

---

collections/voip-and-video-conferencing.yml

- ident: network-communication-software
name: Network Communication Software
name_cn: 网络通信软件

更新VoIP和视频会议

---

collections/5g-mobile-communication.yml

- ident: network-communication-software
name: Network Communication Software
name_cn: 网络通信软件

新增5G通信-移动通信

---

collections/new-retail-network-store-and-mall.yml

https://gitee.com/ZhongBangKeJi/CRMEB

fix: new-retail-network-store-and-mall contains a duplicate value

---

collections/geographic-information-system.yml

- ident: geographic-information-software
name: Geographic Information Software
name_cn: 地理信息软件

更新地理信息系统（GIS）

---

collections/geographic-information-processing-software.yml

- ident: geographic-information-software
name: Geographic Information Software
name_cn: 地理信息软件

新增地理信息加工处理软件

---

single-repositories/github/verygoodgraphics/vgg_runtime/.yml

Reverts oss-compass/compass-projects-information#1020

Revert "Updated single-repositories/github/verygoodgraphics/vgg_runtime/.yml"

---

collections.yml

Add two level 1 category, general-management-software and multi-media-software
all level 2 category already added.

Add two level 1 category

---

collections/electronic-design-automation-EDA.yml

ident: science-and-engineering-calculation
name: Science and Engineering Calculation
name_cn: 科学和工程计算

新增电子设计自动化（EDA）
